# EJECUTA RUTINAS DE INTERSECCIÓN DE ARCHIVOS
# FALTA ARREGLAR LA INTERSECCIÓN EN EL CASO DE EXISTENCIA DE DATOS, NO ESTÁ FUNCIONANDO BIEN

import arcpy

exec (open(r"Q:/09 SISTEMAS INFORMATICOS/GIS_PYTON/identity.py").read())
exec (open(r"Q:/09 SISTEMAS INFORMATICOS/GIS_PYTON/campo.py").read())

SHPIDEN = r"Y:/0_SIG_PROCESO/01 PAIS.mdb/Sistema_Urbano_Nacional"
SHP = r"Y:/0_SIG_PROCESO/MAPAS/TEMPORAL/SISTEMA1.shp"
identi(SHPIDEN,SHP)

CAMPO = "NOM_SUN"
NULO = " "
VAL = "FUERA DE SISTEMA URBANO NACIONAL"
valor(SHP,CAMPO,NULO,VAL,SHPIDEN)

SHPIDEN = r"Y:/0_SIG_PROCESO/00 MEXICO.mdb/CONABIO/AREAS_CONSERVACION_AVES_2015"
identi(SHPIDEN,SHP)

CAMPO = "NOMBRE"
NULO = " "
VAL = "FUERA DE ÁREA DE CONSERVACIÓN DE AVES"
valor(SHP,CAMPO,NULO,VAL,SHPIDEN)


SHPIDEN = r"Y:/0_SIG_PROCESO/00 MEXICO.mdb/CONABIO/CLIMA"
identi(SHPIDEN,SHP)

CAMPO = "CLIMA_TIPO"
NULO = " "
VAL = "FUERA DE CLIMA"
valor(SHP,CAMPO,NULO,VAL,SHPIDEN)